dist: trusty
sudo: required
language: cpp

# Compiler selection
matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env: COMPILER=clang++-4.0

# Build steps
script:
  - rm -rf build
  - mkdir build
  - cd build
  - cmake .. && make
  - ./telegonus